spring.application.name=biblioteca-api
spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:biblioteca12345@biblioteca-cluster.etuusl9.mongodb.net/biblioteca_db?retryWrites=true&w=majority&appName=biblioteca-cluster
spring.data.mongodb.database=biblioteca_db
server.port=8080